version: '3.6'
services:
  web:
    tty: true
    stdin_open: true
    command: sh /docker-entrypoint.sh
    build: ./docker/web
    ports: 
      - '8080:8080'
    volumes:
      - "/app/node_modules" 
      - ".:/app"
